name: development tests

on:
  push:
    branches: [main]
    paths:
      - 'plugins/development/**'
  pull_request:
    paths:
      - 'plugins/development/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugins/development
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run tests
        run: npm test
